import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search, Plus, Users, Github, Linkedin, ArrowRight, Sparkles, X, Check, UserRound, LayoutDashboard, LogOut, Menu} from 'lucide-react';
import './styles.css';

const seedProjects=[
 {id:1,title:'AgroSound AI',description:'An AI-powered platform that turns soil and farm data into useful insights for smart farming.',skills:['Python','Machine Learning','React'],members:2,max:4,owner:'Kumar',category:'AI & ML',status:'Recruiting'},
 {id:2,title:'Campus Connect',description:'A platform where students discover campus clubs, events and communities in one place.',skills:['React','Node.js','UI/UX'],members:3,max:5,owner:'Aarav',category:'Web Development',status:'Recruiting'},
 {id:3,title:'StudyMate',description:'Find study partners, share notes and organize preparation around upcoming exams.',skills:['React','Firebase','Figma'],members:1,max:4,owner:'Priya',category:'EdTech',status:'Recruiting'},
 {id:4,title:'EcoTrack',description:'Track everyday habits and visualize personal sustainability goals.',skills:['Python','Data Science','Flutter'],members:4,max:5,owner:'Rohan',category:'Data Science',status:'Almost full'}
];

function App(){
 const [page,setPage]=useState('home'); const [projects,setProjects]=useState(seedProjects); const [query,setQuery]=useState(''); const [showCreate,setShowCreate]=useState(false); const [toast,setToast]=useState(''); const [menu,setMenu]=useState(false); const [profile,setProfile]=useState({name:'Kumar Anubhava',college:'KL University',bio:'AI & Data Science student building useful products.',skills:['Python','AI/ML','React','Data Science']});
 const filtered=useMemo(()=>projects.filter(p=>(p.title+' '+p.description+' '+p.skills.join(' ')+' '+p.category).toLowerCase().includes(query.toLowerCase())),[projects,query]);
 const notify=(m)=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const createProject=(data)=>{setProjects([{...data,id:Date.now(),members:1,max:Number(data.max),owner:profile.name.split(' ')[0],status:'Recruiting'},...projects]);setShowCreate(false);setPage('projects');notify('Project published successfully!')};
 return <div className="app">
  <header className="nav"><div className="brand" onClick={()=>setPage('home')}><span className="brandMark">P</span><span>Project<span>Hub</span></span></div>
   <nav className={menu?'open':''}><button className={page==='home'?'active':''} onClick={()=>{setPage('home');setMenu(false)}}>Home</button><button className={page==='projects'?'active':''} onClick={()=>{setPage('projects');setMenu(false)}}>Explore</button><button className={page==='profile'?'active':''} onClick={()=>{setPage('profile');setMenu(false)}}>My Profile</button></nav>
   <div className="navActions"><button className="outline hideMobile" onClick={()=>setShowCreate(true)}><Plus size={17}/> Create Project</button><button className="avatar" onClick={()=>setPage('profile')}>KA</button><button className="mobileMenu" onClick={()=>setMenu(!menu)}><Menu/></button></div>
  </header>
  {page==='home' && <Home setPage={setPage} setShowCreate={setShowCreate}/>} 
  {page==='projects' && <Explore projects={filtered} query={query} setQuery={setQuery} onApply={notify}/>} 
  {page==='profile' && <Profile profile={profile} setProfile={setProfile} notify={notify}/>} 
  {showCreate && <CreateModal onClose={()=>setShowCreate(false)} onCreate={createProject}/>} 
  {toast && <div className="toast"><Check size={17}/>{toast}</div>}
  <footer><div><b>ProjectHub</b><span> Build together. Grow together.</span></div><span>© 2026 ProjectHub</span></footer>
 </div>
}

function Home({setPage,setShowCreate}){return <main>
 <section className="hero"><div className="heroCopy"><div className="pill"><Sparkles size={15}/> Built for student builders</div><h1>Find your people.<br/><em>Build something real.</em></h1><p>ProjectHub helps students find teammates, launch projects and turn ideas into something they can proudly put on their portfolio.</p><div className="heroBtns"><button className="primary" onClick={()=>setPage('projects')}>Explore Projects <ArrowRight size={18}/></button><button className="secondary" onClick={()=>setShowCreate(true)}><Plus size={18}/> Start a Project</button></div><div className="trust"><div className="faces"><span>KA</span><span>AR</span><span>PS</span><span>+</span></div><div><b>Build with students</b><small>Find teammates with the skills you need.</small></div></div></div><div className="heroCard"><div className="cardTop"><span>PROJECT MATCH</span><span className="live"><i/> LIVE</span></div><div className="matchProject"><div className="projectIcon">🌱</div><div><h3>AgroSound AI</h3><p>AI & Smart Farming</p></div></div><div className="need"><span>Looking for</span><b>React Developer</b><b>UI/UX Designer</b></div><div className="matchLine"><div className="miniAvatar">KA</div><div className="line"/><div className="miniAvatar alt">RS</div><div className="matchBadge">92% match</div></div><button className="cardButton">View project <ArrowRight size={16}/></button></div></section>
 <section className="stats"><div><b>01</b><span>Create your profile</span></div><div><b>02</b><span>Discover projects</span></div><div><b>03</b><span>Join a team</span></div><div><b>04</b><span>Build & showcase</span></div></section>
 <section className="feature"><div><span className="eyebrow">WHY PROJECTHUB</span><h2>From “I have an idea”<br/>to “We built it.”</h2><p>Stop searching for teammates in random group chats. Put your skills out there and find people who are excited to build the same kind of things.</p></div><div className="featureGrid"><Feature icon="🧩" title="Find teammates" text="Search by skills, interests and project type."/><Feature icon="🚀" title="Launch projects" text="Turn your idea into a real team and roadmap."/><Feature icon="✨" title="Build your portfolio" text="Showcase what you actually built, not just courses."/><Feature icon="🤖" title="AI matching" text="Coming soon: intelligent teammate recommendations."/></div></section>
 </main>}
function Feature({icon,title,text}){return <div className="featureItem"><span>{icon}</span><div><h3>{title}</h3><p>{text}</p></div></div>}
function Explore({projects,query,setQuery,onApply}){return <main className="container"><div className="pageHead"><div><span className="eyebrow">DISCOVER</span><h1>Projects looking for you.</h1><p>Find an idea that matches your skills and join a team.</p></div><button className="primary" onClick={()=>onApply('Use “Create Project” in the top bar to publish your idea.') }><Plus size={18}/> Create project</button></div><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects, skills, technologies..."/><span>{projects.length} projects</span></div><div className="grid">{projects.map(p=><ProjectCard key={p.id} p={p} onApply={onApply}/>)}</div>{!projects.length&&<div className="empty"><Search size={35}/><h3>No projects found</h3><p>Try another skill or keyword.</p></div>}</main>}
function ProjectCard({p,onApply}){return <article className="projectCard"><div className="projectMeta"><span className="category">{p.category}</span><span className={p.status==='Almost full'?'warning':'status'}>{p.status}</span></div><div className="projectTitle"><div className="projectIcon">{p.title[0]}</div><div><h3>{p.title}</h3><small>by {p.owner}</small></div></div><p>{p.description}</p><div className="skills">{p.skills.map(s=><span key={s}>{s}</span>)}</div><div className="cardFoot"><span><Users size={16}/> {p.members}/{p.max} members</span><button onClick={()=>onApply(`Application sent to ${p.title}!`)}>Apply <ArrowRight size={15}/></button></div></article>}
function Profile({profile,setProfile,notify}){const [edit,setEdit]=useState(false);return <main className="container profilePage"><div className="profileHero"><div className="bigAvatar">KA</div><div><span className="eyebrow">MY PROFILE</span><h1>{profile.name}</h1><p>{profile.college} · AI & Data Science</p></div><button className="outline" onClick={()=>setEdit(!edit)}>{edit?'Done':'Edit Profile'}</button></div>{edit?<div className="editBox"><label>Name<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>College<input value={profile.college} onChange={e=>setProfile({...profile,college:e.target.value})}/></label><label>Bio<textarea value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})}/></label><button className="primary" onClick={()=>{setEdit(false);notify('Profile updated')}}>Save changes</button></div>:<div className="profileGrid"><section className="panel"><h2>About</h2><p>{profile.bio}</p><div className="links"><span><Github size={17}/> GitHub</span><span><Linkedin size={17}/> LinkedIn</span></div></section><section className="panel"><h2>Skills</h2><div className="skills large">{profile.skills.map(s=><span key={s}>{s}</span>)}</div></section></div>}</main>}
function CreateModal({onClose,onCreate}){const [f,setF]=useState({title:'',description:'',skills:'',max:4,category:'Web Development'});const submit=e=>{e.preventDefault();if(!f.title||!f.description||!f.skills)return;onCreate({...f,skills:f.skills.split(',').map(x=>x.trim()).filter(Boolean)})};return <div className="modalBg" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><button className="close" onClick={onClose}><X/></button><span className="eyebrow">NEW PROJECT</span><h2>What are you building?</h2><p>Tell other students what you need help with.</p><form onSubmit={submit}><label>Project name<input required placeholder="e.g. AI Study Assistant" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Description<textarea required placeholder="What are you building and why?" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><div className="two"><label>Category<select value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option>Web Development</option><option>AI & ML</option><option>Data Science</option><option>Mobile</option><option>EdTech</option><option>Other</option></select></label><label>Team size<input type="number" min="2" max="20" value={f.max} onChange={e=>setF({...f,max:e.target.value})}/></label></div><label>Skills needed <small>comma separated</small><input required placeholder="React, Python, UI/UX" value={f.skills} onChange={e=>setF({...f,skills:e.target.value})}/></label><button className="primary full">Publish project <ArrowRight size={17}/></button></form></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
